name = "fedra-bot"
main = "main.py"
compatibility_date = "2024-03-07"
compatibility_flags = ["python_workers"]

[vars]
TELEGRAM_BOT_TOKEN = "8294696946:AAE_AAfoilyktfUKRpR8QFquClbPxrOLE44"
GROQ_API_KEY = "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"
